# Generated by Django 6.0.6 on 2026-06-05 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование коллекции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название роли')),
                ('clearance_level', models.PositiveIntegerField(default=1, verbose_name='Уровень допуска')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование мастерской')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание мастерской')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workshops/%Y/%m/%d', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Мастерская',
                'verbose_name_plural': 'Мастерские',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование снаряжения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание снаряжения')),
                ('price', models.FloatField(verbose_name='Цена (Ankh)')),
                ('level', models.PositiveBigIntegerField(default=1, verbose_name='Уровень опасности/силы')),
                ('color', models.CharField(max_length=255, verbose_name='Преобладающий цвет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/%Y/%m/%d', verbose_name='Изображение')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Доступность к заказу')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silenceShop.category', verbose_name='Категория')),
                ('collection', models.ManyToManyField(to='silenceShop.collection', verbose_name='Коллекции')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='silenceShop.workshop', verbose_name='Мастерская')),
            ],
            options={
                'verbose_name': 'Позиция снаряжения',
                'verbose_name_plural': 'Позиции снаряжения',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silenceShop.equipment', verbose_name='Снаряжение')),
            ],
            options={
                'verbose_name': 'Предмет в корзине',
                'verbose_name_plural': 'Предметы в корзине',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Оценка силы (1-5)')),
                ('comment', models.TextField(verbose_name='Комментарий фиксера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='silenceShop.equipment', verbose_name='Снаряжение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Фиксер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='FixerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d', verbose_name='Изображение профиля')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Досье фиксера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silenceShop.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Профиль фиксера',
                'verbose_name_plural': 'Профили фиксеров',
            },
        ),
    ]
