# Generated by Django 6.0.6 on 2026-06-05 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silenceShop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Утвержден'), ('completed', 'Выполнен')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('total_price', models.FloatField(default=0.0, verbose_name='Итоговая стоимость (Ankh)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Фиксер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена при оформлении')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silenceShop.equipment', verbose_name='Снаряжение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='silenceShop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Предмет заказа',
                'verbose_name_plural': 'Предметы заказа',
            },
        ),
    ]
